/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticContent: typeof import('./components/Analytics/AnalyticContent.vue')['default']
    AnalyticsPanel: typeof import('./components/AnalyticsPanel.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    InlineLoading: typeof import('./components/InlineLoading.vue')['default']
    PageLoading: typeof import('./components/PageLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsCards: typeof import('./components/StatisticsCards.vue')['default']
  }
}
