/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/home/analytics': RouteRecordInfo<'/home/analytics', '/home/analytics', Record<never, never>, Record<never, never>>,
    '/home/article': RouteRecordInfo<'/home/article', '/home/article', Record<never, never>, Record<never, never>>,
    '/home/detail/[articleId]': RouteRecordInfo<'/home/detail/[articleId]', '/home/detail/:articleId', { articleId: ParamValue<true> }, { articleId: ParamValue<false> }>,
    '/loading-demo': RouteRecordInfo<'/loading-demo', '/loading-demo', Record<never, never>, Record<never, never>>,
    '/personal/history': RouteRecordInfo<'/personal/history', '/personal/history', Record<never, never>, Record<never, never>>,
    '/typescript-demo': RouteRecordInfo<'/typescript-demo', '/typescript-demo', Record<never, never>, Record<never, never>>,
  }
}
